id: P003236
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 10:49:22.449249
source_metadata:
  id: bdr:W00KG03685
  title: སྐད་ཆའི་ལང་ཚོ
  author: ''
  volumes:
    b9b8121751f748f3a247b33c3681b746:
      image_group_id: I00KG03768
      title: ''
      volume_number: 1
      total_pages: 234
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
